import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:lifelog_reference/models/record.dart';
import 'package:lifelog_reference/database/mock_record_repository.dart';
import 'package:lifelog_reference/services/date_service.dart';
import 'package:lifelog_reference/theme/lifelog_theme.dart';
import 'package:lifelog_reference/widgets/journal_screen.dart';
import 'package:lifelog_reference/widgets/search_screen.dart';

// Set a fixed logical pixel window for stable golden output.
// Phone-like dimensions to show full screen layout.
void _setWindowSize(WidgetTester tester,
    {double width = 400, double height = 800}) {
  tester.view.physicalSize = Size(width, height);
  tester.view.devicePixelRatio = 1.0;
  addTearDown(tester.view.resetPhysicalSize);
  addTearDown(tester.view.resetDevicePixelRatio);
}

// Build a MockRecordRepository seeded with realistic data for today and
// recent days, covering all record types. Uses DateService so dates are
// dynamic — goldens are regenerated by CI on widget/test changes.
MockRecordRepository _mockRepo() {
  final today = DateService.today();
  final yesterday = DateService.getDateForOffset(-1);
  final twoDaysAgo = DateService.getDateForOffset(-2);

  return MockRecordRepository(
    initialData: {
      today: [
        Record(
          id: 'scr-1',
          date: today,
          type: RecordType.heading,
          content: 'Morning',
          metadata: {'heading.level': 1},
          orderPosition: 1.0,
          createdAt: 0,
          updatedAt: 0,
        ),
        Record(
          id: 'scr-2',
          date: today,
          type: RecordType.todo,
          content: 'Review pull requests',
          metadata: {'todo.checked': false},
          orderPosition: 2.0,
          createdAt: 0,
          updatedAt: 0,
        ),
        Record(
          id: 'scr-3',
          date: today,
          type: RecordType.todo,
          content: 'Ship new feature',
          metadata: {'todo.checked': true},
          orderPosition: 3.0,
          createdAt: 0,
          updatedAt: 0,
        ),
        Record(
          id: 'scr-4',
          date: today,
          type: RecordType.text,
          content: 'Met with the team about the new architecture',
          metadata: {},
          orderPosition: 4.0,
          createdAt: 0,
          updatedAt: 0,
        ),
        Record(
          id: 'scr-5',
          date: today,
          type: RecordType.bulletList,
          content: 'Discussed migration strategy',
          metadata: {'bulletList.indentLevel': 0},
          orderPosition: 5.0,
          createdAt: 0,
          updatedAt: 0,
        ),
        Record(
          id: 'scr-6',
          date: today,
          type: RecordType.bulletList,
          content: 'Database schema changes',
          metadata: {'bulletList.indentLevel': 1},
          orderPosition: 6.0,
          createdAt: 0,
          updatedAt: 0,
        ),
        Record(
          id: 'scr-7',
          date: today,
          type: RecordType.habit,
          content: 'Meditation',
          metadata: {
            'habit.name': 'Meditation',
            'habit.frequency': 'daily',
            'habit.completions': [today, yesterday],
          },
          orderPosition: 7.0,
          createdAt: 0,
          updatedAt: 0,
        ),
      ],
      yesterday: [
        Record(
          id: 'scr-8',
          date: yesterday,
          type: RecordType.heading,
          content: 'Afternoon',
          metadata: {'heading.level': 2},
          orderPosition: 1.0,
          createdAt: 0,
          updatedAt: 0,
        ),
        Record(
          id: 'scr-9',
          date: yesterday,
          type: RecordType.text,
          content: 'Deployed v2.1 to production successfully',
          metadata: {},
          orderPosition: 2.0,
          createdAt: 0,
          updatedAt: 0,
        ),
        Record(
          id: 'scr-10',
          date: yesterday,
          type: RecordType.bulletList,
          content: 'Wrote integration tests',
          metadata: {'bulletList.indentLevel': 0},
          orderPosition: 3.0,
          createdAt: 0,
          updatedAt: 0,
        ),
        Record(
          id: 'scr-11',
          date: yesterday,
          type: RecordType.todo,
          content: 'Update documentation',
          metadata: {'todo.checked': true},
          orderPosition: 4.0,
          createdAt: 0,
          updatedAt: 0,
        ),
      ],
      twoDaysAgo: [
        Record(
          id: 'scr-12',
          date: twoDaysAgo,
          type: RecordType.heading,
          content: 'Sprint Planning',
          metadata: {'heading.level': 1},
          orderPosition: 1.0,
          createdAt: 0,
          updatedAt: 0,
        ),
        Record(
          id: 'scr-13',
          date: twoDaysAgo,
          type: RecordType.text,
          content: 'Planned features for the next sprint cycle',
          metadata: {},
          orderPosition: 2.0,
          createdAt: 0,
          updatedAt: 0,
        ),
      ],
    },
  );
}

void main() {
  group('JournalScreen', () {
    testWidgets('with mock data', (tester) async {
      _setWindowSize(tester);
      final repo = _mockRepo();

      await tester.pumpWidget(
        LifelogTokens(
          child: MaterialApp(
            theme: LifelogTheme.light(),
            debugShowCheckedModeBanner: false,
            home: JournalScreen(repository: repo),
          ),
        ),
      );
      // Multiple pump cycles: JournalScreen loads data in initState via async,
      // then DaySection uses FutureBuilder which needs another frame to deliver.
      await tester.pumpAndSettle();

      await expectLater(
        find.byType(MaterialApp),
        matchesGoldenFile('../goldens/journal_screen.png'),
      );
    });
  });

  group('SearchScreen', () {
    testWidgets('empty state', (tester) async {
      _setWindowSize(tester);
      final repo = _mockRepo();

      await tester.pumpWidget(
        LifelogTokens(
          child: MaterialApp(
            theme: LifelogTheme.light(),
            debugShowCheckedModeBanner: false,
            home: SearchScreen(repository: repo),
          ),
        ),
      );
      await tester.pumpAndSettle();

      await expectLater(
        find.byType(MaterialApp),
        matchesGoldenFile('../goldens/search_screen_empty.png'),
      );
    });

    testWidgets('with results', (tester) async {
      _setWindowSize(tester);
      final repo = _mockRepo();

      await tester.pumpWidget(
        LifelogTokens(
          child: MaterialApp(
            theme: LifelogTheme.light(),
            debugShowCheckedModeBanner: false,
            home: SearchScreen(repository: repo),
          ),
        ),
      );
      await tester.pumpAndSettle();

      // Type a query that matches records across multiple days.
      await tester.enterText(find.byType(TextField), 'the');
      // Debouncer delays 500ms before firing the search.
      await tester.pump(const Duration(milliseconds: 600));
      await tester.pumpAndSettle();

      await expectLater(
        find.byType(MaterialApp),
        matchesGoldenFile('../goldens/search_screen_results.png'),
      );
    });
  });
}
